# Generated by Django 3.0.6 on 2020-05-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('natureza', models.CharField(blank=True, max_length=150, null=True)),
                ('comportamento', models.CharField(blank=True, max_length=150, null=True)),
                ('cla', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True)),
                ('senhor', models.CharField(blank=True, max_length=150, null=True)),
                ('conceito', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forca', models.IntegerField(default=1, null=True)),
                ('destreza', models.IntegerField(default=1, null=True)),
                ('vigor', models.IntegerField(default=1, null=True)),
                ('carisma', models.IntegerField(default=1, null=True)),
                ('manipulacao', models.IntegerField(default=1, null=True)),
                ('aparencia', models.IntegerField(default=1, null=True)),
                ('percepcao', models.IntegerField(default=1, null=True)),
                ('inteligencia', models.IntegerField(default=1, null=True)),
                ('raciocinio', models.IntegerField(default=1, null=True)),
                ('prontidao', models.IntegerField(default=0, null=True)),
                ('esportes', models.IntegerField(default=0, null=True)),
                ('briga', models.IntegerField(default=0, null=True)),
                ('esquiva', models.IntegerField(default=0, null=True)),
                ('empatia', models.IntegerField(default=0, null=True)),
                ('expressao', models.IntegerField(default=0, null=True)),
                ('intimidacao', models.IntegerField(default=0, null=True)),
                ('lideranca', models.IntegerField(default=0, null=True)),
                ('manha', models.IntegerField(default=0, null=True)),
                ('labia', models.IntegerField(default=0, null=True)),
                ('empatia_animais', models.IntegerField(default=0, null=True)),
                ('oficios', models.IntegerField(default=0, null=True)),
                ('conducao', models.IntegerField(default=0, null=True)),
                ('etiqueta', models.IntegerField(default=0, null=True)),
                ('armas_fogo', models.IntegerField(default=0, null=True)),
                ('armas_branca', models.IntegerField(default=0, null=True)),
                ('performance', models.IntegerField(default=0, null=True)),
                ('seguranca', models.IntegerField(default=0, null=True)),
                ('furtividade', models.IntegerField(default=0, null=True)),
                ('sobrevivencia', models.IntegerField(default=0, null=True)),
                ('academicos', models.IntegerField(default=0, null=True)),
                ('computador', models.IntegerField(default=0, null=True)),
                ('financas', models.IntegerField(default=0, null=True)),
                ('investigacao', models.IntegerField(default=0, null=True)),
                ('direito', models.IntegerField(default=0, null=True)),
                ('linguistica', models.IntegerField(default=0, null=True)),
                ('medicina', models.IntegerField(default=0, null=True)),
                ('ocultismo', models.IntegerField(default=0, null=True)),
                ('politico', models.IntegerField(default=0, null=True)),
                ('ciencia', models.IntegerField(default=0, null=True)),
                ('defesa', models.IntegerField(blank=True, null=True)),
                ('iniciativa', models.IntegerField(blank=True, null=True)),
                ('deslocamento', models.IntegerField(blank=True, null=True)),
                ('consciencia', models.IntegerField(blank=True, null=True)),
                ('autocontrole', models.IntegerField(blank=True, null=True)),
                ('coragem', models.IntegerField(blank=True, null=True)),
                ('humanidade', models.IntegerField(blank=True, null=True)),
                ('forca_vontade', models.IntegerField(blank=True, null=True)),
                ('forca_vontade_max', models.IntegerField(blank=True, null=True)),
                ('pontos_sangue', models.IntegerField(blank=True, null=True)),
                ('pontos_sangue_max', models.IntegerField(blank=True, null=True)),
                ('vitalidade', models.IntegerField(blank=True, null=True)),
                ('vitalidade_max', models.IntegerField(blank=True, null=True)),
                ('id_personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Disciplina'), (2, 'Antecendente'), (3, 'Qualidade'), (4, 'Defeito')])),
                ('id_personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personagem')),
            ],
        ),
    ]
