# Generated by Django 3.0.6 on 2020-06-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forca_vontade', models.IntegerField(default=0)),
                ('forca_vontade_max', models.IntegerField(default=0)),
                ('pontos_sangue', models.IntegerField(default=0)),
                ('pontos_sangue_max', models.IntegerField(default=0)),
                ('vitalidade', models.IntegerField(default=0)),
                ('vitalidade_max', models.IntegerField(default=0)),
                ('experiencia', models.IntegerField(default=0)),
                ('forca', models.IntegerField(default=1, null=True)),
                ('destreza', models.IntegerField(default=1, null=True)),
                ('vigor', models.IntegerField(default=1, null=True)),
                ('carisma', models.IntegerField(default=1, null=True)),
                ('manipulacao', models.IntegerField(default=1, null=True)),
                ('aparencia', models.IntegerField(default=1, null=True)),
                ('percepcao', models.IntegerField(default=1, null=True)),
                ('inteligencia', models.IntegerField(default=1, null=True)),
                ('raciocinio', models.IntegerField(default=1, null=True)),
                ('defesa', models.IntegerField(blank=True, null=True)),
                ('iniciativa', models.IntegerField(blank=True, null=True)),
                ('deslocamento', models.IntegerField(blank=True, null=True)),
                ('consciencia', models.IntegerField(blank=True, null=True)),
                ('autocontrole', models.IntegerField(blank=True, null=True)),
                ('coragem', models.IntegerField(blank=True, null=True)),
                ('humanidade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('natureza', models.CharField(blank=True, max_length=150, null=True)),
                ('comportamento', models.CharField(blank=True, max_length=150, null=True)),
                ('cla', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True)),
                ('senhor', models.CharField(blank=True, max_length=150, null=True)),
                ('conceito', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Talento'), (2, 'Pericia'), (3, 'Conhecimento')])),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('valor', models.IntegerField(default=0, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ficha')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='id_personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personagem'),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Disciplina'), (2, 'Antecendente'), (3, 'Qualidade'), (4, 'Defeito'), (5, 'Inventario')])),
                ('id_personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personagem')),
            ],
        ),
    ]
