# Generated by Django 3.0.6 on 2020-05-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Disciplina'), (2, 'Antecendente'), (3, 'Qualidade'), (4, 'Defeito'), (5, 'Inventario')]),
        ),
    ]
