# Generated by Django 3.0.6 on 2020-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='academicos',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='armas_branca',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='armas_fogo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='briga',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ciencia',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='computador',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='conducao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='direito',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='empatia',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='empatia_animais',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='esportes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='esquiva',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='etiqueta',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='expressao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='financas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='furtividade',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='intimidacao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='investigacao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='labia',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='lideranca',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='linguistica',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='manha',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='medicina',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ocultismo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='oficios',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='performance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='politico',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='prontidao',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='seguranca',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sobrevivencia',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
