# Generated by Django 3.0.6 on 2020-06-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='forca_vontade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='forca_vontade_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pontos_sangue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pontos_sangue_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='vitalidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='vitalidade_max',
            field=models.IntegerField(default=0),
        ),
    ]
