# Generated by Django 3.0.6 on 2020-05-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200530_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='token',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
