# Generated by Django 3.0.7 on 2020-06-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200605_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_Cthulhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_vida', models.IntegerField(default=0)),
                ('pontos_vida_max', models.IntegerField(default=0)),
                ('sanidade', models.IntegerField(default=0)),
                ('sanidade_max', models.IntegerField(default=0)),
                ('FOR', models.IntegerField(default=1, null=True)),
                ('CON', models.IntegerField(default=1, null=True)),
                ('TAM', models.IntegerField(default=1, null=True)),
                ('DES', models.IntegerField(default=1, null=True)),
                ('APA', models.IntegerField(default=1, null=True)),
                ('EDU', models.IntegerField(default=1, null=True)),
                ('INT', models.IntegerField(default=1, null=True)),
                ('POD', models.IntegerField(default=1, null=True)),
                ('taxa_mov', models.IntegerField(default=1, null=True)),
                ('id_personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personagem')),
            ],
        ),
    ]
