# Generated by Django 3.0.7 on 2020-06-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ficha_cthulhu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade_Cthulhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('valor', models.IntegerField(default=0, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ficha_Cthulhu')),
            ],
        ),
    ]
