# Generated by Django 3.0.7 on 2020-06-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_habilidade_cthulhu'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade_cthulhu',
            name='coluna',
            field=models.IntegerField(choices=[(1, 'Coluna 1'), (2, 'Coluna 2'), (3, 'Coluna 3'), (4, 'Coluna 4')], default=1),
        ),
    ]
