# Generated by Django 3.0.7 on 2020-06-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_habilidade_cthulhu_coluna'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='APA_bom',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='APA_extremo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='CON_bom',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='CON_extremo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='DES_bom',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='DES_extremo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='EDU_bom',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='EDU_extremo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='FOR_bom',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='FOR_extremo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='INT_bom',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='INT_extremo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='POD_bom',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='POD_extremo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='TAM_bom',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ficha_cthulhu',
            name='TAM_extremo',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
