# Generated by Django 3.0.7 on 2020-06-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200607_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sistema', models.IntegerField(choices=[(1, 'Talento'), (2, 'Pericia'), (3, 'Conhecimento')])),
                ('mestre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='extra',
            options={'verbose_name': 'extra', 'verbose_name_plural': 'extras'},
        ),
        migrations.AlterModelOptions(
            name='ficha',
            options={'verbose_name': 'ficha', 'verbose_name_plural': 'fichas'},
        ),
        migrations.AlterModelOptions(
            name='ficha_cthulhu',
            options={'verbose_name': 'ficha_cthulhu', 'verbose_name_plural': 'fichas_cthulhu'},
        ),
        migrations.AlterModelOptions(
            name='habilidade',
            options={'ordering': ['titulo'], 'verbose_name': 'habilidade', 'verbose_name_plural': 'habilidades'},
        ),
        migrations.AlterModelOptions(
            name='habilidade_cthulhu',
            options={'ordering': ['titulo'], 'verbose_name': 'habilidade_cthulhu', 'verbose_name_plural': 'habilidades_cthulhu'},
        ),
        migrations.AlterModelOptions(
            name='personagem',
            options={'verbose_name': 'personagem', 'verbose_name_plural': 'personagens'},
        ),
        migrations.AddField(
            model_name='personagem',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Mesa'),
        ),
    ]
