# Generated by Django 3.0.7 on 2020-06-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200612_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Disciplina'), (2, 'Antecendente'), (3, 'Qualidade'), (4, 'Defeito')])),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'descricao',
                'verbose_name_plural': 'descricoes',
            },
        ),
    ]
