# Generated by Django 3.0.7 on 2020-06-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='dificuldade',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='descricao',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='descricao',
            name='sistema',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='descricao',
            name='teste',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
