# Generated by Django 3.0.7 on 2020-06-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200613_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
