# Generated by Django 3.0.7 on 2020-06-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_descricao_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
    ]
