# Generated by Django 3.0.7 on 2020-06-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200618_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilidade',
            new_name='Habilidade_Vampiro',
        ),
    ]
