from django.db import models

# Create your models here.
class personagem_vampiro(models.Model):
    nome = models.CharField(max_length=200)
    idade = models.IntegerField(null=True, blank=True)
    natureza = models.CharField(max_length=150, null=True, blank=True)
    comportamento = models.CharField(max_length=150, null=True, blank=True)
    cla = models.CharField(max_length=100, null=True, blank=True)
    ocupacao = models.CharField(max_length=100, null=True, blank=True)
    senhor = models.CharField(max_length=150, null=True, blank=True)
    conceito = models.CharField(max_length=150, null=True, blank=True)

class ficha_vampiro(models.Model):
    id_personagem = models.ForeignKey('personagem_vampiro', on_delete=models.CASCADE)

    ############### Atributos ###############
    forca = models.IntegerField(null=True, blank=True)
    destreza = models.IntegerField(null=True, blank=True)
    vigor = models.IntegerField(null=True, blank=True)
    carisma = models.IntegerField(null=True, blank=True)
    manipulacao = models.IntegerField(null=True, blank=True)
    aparencia = models.IntegerField(null=True, blank=True)
    percepcao = models.IntegerField(null=True, blank=True)
    inteligencia = models.IntegerField(null=True, blank=True)
    raciocinio = models.IntegerField(null=True, blank=True)

    ############### Habilidades ###############
    prontidao = models.IntegerField(null=True, blank=True)
    esportes = models.IntegerField(null=True, blank=True)
    briga = models.IntegerField(null=True, blank=True)
    esquiva = models.IntegerField(null=True, blank=True)
    empatia = models.IntegerField(null=True, blank=True)
    expressao = models.IntegerField(null=True, blank=True)
    intimidacao = models.IntegerField(null=True, blank=True)
    lideranca = models.IntegerField(null=True, blank=True)
    manha = models.IntegerField(null=True, blank=True)
    empatia_animais = models.IntegerField(null=True, blank=True)
    oficios = models.IntegerField(null=True, blank=True)
    conducao = models.IntegerField(null=True, blank=True)
    etiqueta = models.IntegerField(null=True, blank=True)
    armas_fogo = models.IntegerField(null=True, blank=True)
    armas_branca = models.IntegerField(null=True, blank=True)
    performance = models.IntegerField(null=True, blank=True)
    seguranca = models.IntegerField(null=True, blank=True)
    furtividade = models.IntegerField(null=True, blank=True)
    sobrevivencia = models.IntegerField(null=True, blank=True)
    academicos = models.IntegerField(null=True, blank=True)
    computador = models.IntegerField(null=True, blank=True)
    financas = models.IntegerField(null=True, blank=True)
    investigacao = models.IntegerField(null=True, blank=True)
    direito = models.IntegerField(null=True, blank=True)
    linguistica = models.IntegerField(null=True, blank=True)
    medicina = models.IntegerField(null=True, blank=True)
    ocultismo = models.IntegerField(null=True, blank=True)
    politico = models.IntegerField(null=True, blank=True)
    ciencia = models.IntegerField(null=True, blank=True)

    ############### Virtudes ###############
    defesa = models.IntegerField(null=True, blank=True)
    iniciativa = models.IntegerField(null=True, blank=True)
    deslocamento = models.IntegerField(null=True, blank=True)
    consciencia = models.IntegerField(null=True, blank=True)
    autocontrole = models.IntegerField(null=True, blank=True)
    coragem = models.IntegerField(null=True, blank=True)
    humanidade = models.IntegerField(null=True, blank=True)
    forca_vontade = models.IntegerField(null=True, blank=True)
    forca_vontade_max = models.IntegerField(null=True, blank=True)
    pontos_sangue = models.IntegerField(null=True, blank=True)
    pontos_sangue_max = models.IntegerField(null=True, blank=True)
    vitalidade = models.IntegerField(null=True, blank=True)
    vitalidade_max = models.IntegerField(null=True, blank=True)

    ############### Disciplinas e Antecendentes ###############
    disciplina_1 = models.CharField(max_length=150, null=True, blank=True)
    disciplina_valor_1 = models.IntegerField(null=True, blank=True)
    disciplina_2 = models.CharField(max_length=150, null=True, blank=True)
    disciplina_valor_2 = models.IntegerField(null=True, blank=True)
    disciplina_3 = models.CharField(max_length=150, null=True, blank=True)
    disciplina_valor_3 = models.IntegerField(null=True, blank=True)
    disciplina_4 = models.CharField(max_length=150, null=True, blank=True)
    disciplina_valor_4 = models.IntegerField(null=True, blank=True)
    disciplina_5 = models.CharField(max_length=150, null=True, blank=True)
    disciplina_valor_5 = models.IntegerField(null=True, blank=True)
    disciplina_6 = models.CharField(max_length=150, null=True, blank=True)
    disciplina_valor_6 = models.IntegerField(null=True, blank=True)
    antecendentes_1 = models.CharField(max_length=150, null=True, blank=True)
    antecendentes_valor_1 = models.IntegerField(null=True, blank=True)
    antecendentes_2 = models.CharField(max_length=150, null=True, blank=True)
    antecendentes_valor_2 = models.IntegerField(null=True, blank=True)
    antecendentes_3 = models.CharField(max_length=150, null=True, blank=True)
    antecendentes_valor_3 = models.IntegerField(null=True, blank=True)
    antecendentes_4 = models.CharField(max_length=150, null=True, blank=True)
    antecendentes_valor_4 = models.IntegerField(null=True, blank=True)
    antecendentes_5 = models.CharField(max_length=150, null=True, blank=True)
    antecendentes_valor_5 = models.IntegerField(null=True, blank=True)
    antecendentes_6 = models.CharField(max_length=150, null=True, blank=True)
    antecendentes_valor_6 = models.IntegerField(null=True, blank=True)

    ############### Qualidades e Defeitos ###############
    qualidade_1 = models.CharField(max_length=150, null=True, blank=True)
    qualidade_2 = models.CharField(max_length=150, null=True, blank=True)
    qualidade_3 = models.CharField(max_length=150, null=True, blank=True)
    qualidade_4 = models.CharField(max_length=150, null=True, blank=True)
    qualidade_5 = models.CharField(max_length=150, null=True, blank=True)
    qualidade_6 = models.CharField(max_length=150, null=True, blank=True)
    defeito_1 = models.CharField(max_length=150, null=True, blank=True)
    defeito_2 = models.CharField(max_length=150, null=True, blank=True)
    defeito_3 = models.CharField(max_length=150, null=True, blank=True)
    defeito_4 = models.CharField(max_length=150, null=True, blank=True)
    defeito_5 = models.CharField(max_length=150, null=True, blank=True)
    defeito_6 = models.CharField(max_length=150, null=True, blank=True)